### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by Bounce23**
This PR is just to change variable declaration so I can use a certain type in PLONK.

### CODE REVIEW

**Comment by CPerezz** [comment]
The points that you need in PLONK are JubJub points.

So I'm nit sure why you need to access to these attributes there.

**Comment by Bounce23** [comment]
The reason I need the points is because JUBJUB has no implementation for generator of affine coordinates but BLS does. 
The BLS has a file which has affine points and generators on the JUBJUB base field.

**Comment by CPerezz** [comment]
First of all, the JubJub fork that we have, has an implementation for AffinePoint. See:  https://github.com/dusk-network/jubjub/blob/31bd5679694e3620ea0d6ef16fa827c212d42aed/src/lib.rs#L53

Also, it also includes getters for the coordinates. See: https://github.com/dusk-network/jubjub/blob/31bd5679694e3620ea0d6ef16fa827c212d42aed/src/lib.rs#L447

And in the tests they always use the same point which you can define as basepoint in a PR to JubJub. See: https://github.com/dusk-network/jubjub/blob/31bd5679694e3620ea0d6ef16fa827c212d42aed/src/lib.rs#L953

In any case, Bls12 Point structure needs to be modified for any particular reason exposed in this PR.

**Comment by CPerezz** [comment]
I think we can close this @Bounce23

**Comment by Bounce23** [comment]
The JUBJUB relies upon a crate from BLS, so the last comment just allows me to import constants as two scalars, in a struct, into JUBJUB. 

This mismatch between the libraries and types is a bit of a mess imo. @CPerezz

**Comment by Bounce23** [comment]
All of the tests and build are passing. There is only one warning, which is that the new constants aren't used anywhere but thats because they are to be used in JubJub. 

Although this is a fix for the issue, I would like to - in the future - refactor the types and structs etc, as the way they are relied upon for the two libraries, they are not very easy for our use cases.

**Comment by CPerezz** [comment]
Idk if that's needed TBH. The base field relies on the Bls `Scalar` implementation wrapping it up. Which makes complete sense since it avoids duplicating code.

We can discuss it on the next daily.

Feel free to merge this.

**Pull request merged**
